<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-admin.php
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => 'Şuanki aktif araçlar:',
		'add_category_button' => 'Kategori Ekle',
		'add_field_button' => 'Alan Ekle',
		'add_link_button' => 'Bağlantı Ekle',
		'add_link_link' => ' - ^1bağlantı ekle^2',
		'add_new_field' => 'Yeni alan ekle',
		'add_new_title' => 'Yeni Başlık Ekle',
		'add_page_button' => 'Sayfa Ekle',
		'add_title_button' => 'Başlık Ekle',
		'add_widget_button' => 'Araç Ekle',
		'add_widget_link' => ' - ^1araç ekle^2',
		'admin_title' => 'Yönetici Paneli',
		'after_footer' => 'Altbilgideki bağlantıdan sonra ',
		'after_main_menu' => 'Üst sekmelerden sonra',
		'after_x' => '"^"\'den sonra',
		'after_x_tab' => '"^" sekmesinden sonra',
		'approve_user_popup' => 'Kullanıcıyı onayla',
		'approve_users_title' => 'Kullanıcı Onayları',
		'basic_editor' => 'Düz Metin Editör',
		'before_main_menu' => 'Üst sekmelerden önce',
		'blobs_directory_error' => 'The directory ^ defined as QA_BLOBS_DIRECTORY is not writable by the web server.',
		'blobs_move_complete' => 'Yüklenen görüntülerin ve belgelerin taşınması tamamlandı.',
		'blobs_move_moved' => 'Migration ^1 of ^2 uploaded images and documents',
		'blobs_stop' => 'Taşımayı durdurun',
		'blobs_to_db' => 'Blobs to database',
		'blobs_to_db_note' => '- yüklenen tüm görüntüleri ve belgeleri disk dosyalarından veritabanına taşıyın',
		'blobs_to_disk' => 'Blobs to disk',
		'blobs_to_disk_note' => '- yüklenen tüm görüntüleri ve belgeleri veritabanından disk dosyalarına taşıyın',
		'block_button' => 'block',
		'block_ips_note' => 'Birden fazla sayı eşleşmesi için * kullanın. Örnekler: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_user_popup' => 'Kullanıcıyı Engelle',
		'block_words_note' => 'Birden fazla karakter eşleşmesi için * kullanın. Örneğin gözlük*, (gözlükler, gözlükçü); ça*ı, (çatı, çakı, çalı) ile eşleşir.',
		'cancel_mailing_button' => 'Cancel Mailing',
		'categories' => 'Kategoriler',
		'categories_introduction' => 'Kategori eklemek için, \'Kategori Ekle\' butonuna tıklayınız.',
		'categories_not_shown' => 'Bazı soruların görüntülenmeyecek kategorileri vardır.',
		'categories_title' => 'Kategoriler',
		'category_add_sub' => 'Alt Kategori Ekle',
		'category_added' => 'Kategori eklendi',
		'category_already_used' => 'Bu zaten bir kategori tarafından kullanılıyor',
		'category_default_slug' => 'Kategori-^',
		'category_description' => 'Opsiyonel kategori açıklaması:',
		'category_max_depth_x' => 'Some options may be hidden to prevent a category going deeper than ^ levels.',
		'category_move_parent' => 'başka ebeveyne taşı',
		'category_name' => 'Kategori adı:',
		'category_name_first' => 'İlk kategorinin adı:',
		'category_no_add_subs_x' => 'This category cannot have sub-categories because it is already ^ levels down.',
		'category_no_delete_subs' => 'This category cannot be deleted because it has a sub-category.',
		'category_no_sub_error' => '^q question/s in this category have no sub-category - ^1set sub-category^2',
		'category_no_sub_to' => 'Move questions in ^ with no sub-category to:',
		'category_no_subs' => 'Hiçbiri',
		'category_none_error' => '^q soru şuan bir kategoriye sahip değil - ^1kategori ayarla^2',
		'category_none_to' => 'Kategorisiz soruları şuraya taşı::',
		'category_parent' => 'Üst kategori:',
		'category_saved' => 'Kategori kaydedildi',
		'category_slug' => 'Kategori kısa ismi (URL adresindeki adı)',
		'category_subs' => 'Alt kategoriler:',
		'category_top_level' => 'Ebevyn yok (üst seviye)',
		'characters' => 'karakter',
		'check_language_suffix' => ' - ^1dil dosyalarını kontrol et^2',
		'click_name_edit' => 'Özel sayfa veya bağlantılar:',
		'database_cleanup' => 'Veritabanı temizleme işlemleri',
		'delete_category' => 'Bu kategoriyi sil',
		'delete_category_reassign' => 'Bu kategoriyi sil ve içindeki soruları şu kategoriye dahil et:',
		'delete_field' => 'Bu alanı sil',
		'delete_hidden' => 'Gizli gönderileri sil',
		'delete_hidden_complete' => 'All hidden posts without dependents have been deleted',
		'delete_hidden_note' => ' - all hidden questions, answer and comments without dependents',
		'delete_link' => 'Bu bağlantıyı sil',
		'delete_page' => 'Bu sayfayı sil',
		'delete_stop' => 'Silmeyi durdur',
		'delete_title' => 'Bu başlığı sil',
		'delete_widget_position' => 'Bu aracı bu pozisyondan kaldır',
		'edit_custom_page' => 'Özel sayfayı düzenle',
		'edit_field' => ' - ^1alanı düzenle^2',
		'edit_link' => ' - ^1bağlantıyı düzenle^2',
		'edit_page' => ' - ^1sayfayı düzenle^2',
		'edit_title' => ' - ^1başlığı düzenle^2',
		'emails_per_minute' => 'dakika başına e-posta',
		'emails_title' => 'E-Posta',
		'feed_link' => 'Besleme',
		'feed_link_example' => 'Örnek besleme',
		'feeds_title' => 'RSS',
		'field_link_url' => 'URL Adresi',
		'field_multi_line' => 'Çok satırlı yazı',
		'field_name' => 'Alan ismi:',
		'field_single_line' => 'Tek satırlı yazı',
		'field_type' => 'İçerik türü:',
		'first' => 'İlk',
		'flagged_title' => 'İşaretlenmiş',
		'form_security_expired' => 'Form security code expired - please try again',
		'from_anon' => 'Anonimden:',
		'from_users' => 'Kullanıcılardan:',
		'general_title' => 'Genel',
		'hidden_answers_deleted' => 'Deleted ^1 of ^2 hidden answers without dependents...',
		'hidden_comments_deleted' => 'Deleted ^1 of ^2 hidden comments...',
		'hidden_questions_deleted' => 'Deleted ^1 of ^2 hidden questions without dependents...',
		'hidden_title' => 'Gizli',
		'hotness_factors' => 'Soru kaltesi için göreceli önem:',
		'ip_address_pages' => 'IP adresi sayfaları',
		'layout_title' => 'Görünüm',
		'link_name' => 'Bağlantı metni:',
		'link_new_window' => 'Bağlantıyı yeni sekmede aç',
		'link_url' => 'Bağlantının URL adresi:',
		'lists_title' => 'Listeler',
		'mailing_complete' => 'Gönderim tamamlandı',
		'mailing_explanation' => 'Kullanıcılar hesap sayfalarından abonelikten çıkabilir',
		'mailing_progress' => 'Mailing completed for ^1 of ^2 users...',
		'mailing_title' => 'Duyuru',
		'mailing_unsubscribe' => 'Abonelikten çıkma bağlantısı mailin altına eklenecektir.',
		'maintenance_admin_only' => 'Siteniz ^1bakım modundadır^2 ve şuan normal kullanıcılara kapalıdır.',
		'maximum_x' => ' (maks. ^)',
		'moderate_title' => 'Moderasyon',
		'module_x_database_init' => 'The ^1 ^2 module requires some ^3database initialization^4.',
		'most_flagged_title' => 'İşaretlenmiş içerik',
		'mysql_version' => 'MySQL sürümü:',
		'nav_links_explanation' => 'Menüde göster:',
		'nav_qa_is_home' => 'Soru Cevap sayfası (Ana sayfaya bağlantı verilir)',
		'neat_urls_note' => ' (^1htaccess^2 dosyası gerektirir)',
		'no_approve_found' => 'Onay bekleyen içerik bulunamadı',
		'no_classification' => 'Hiçbiri',
		'no_flagged_found' => 'İşaretlenmiş içerik bulunamadı',
		'no_hidden_found' => 'Gizli içerik bulunamadı',
		'no_image_gd' => 'The installed version of PHP was compiled without GD image support, so users cannot upload their avatars directly.',
		'no_link' => 'Bağlantı yok',
		'no_multibyte' => 'The installed version of PHP was compiled without multibyte string support. Searching will be less effective for non-Roman characters.',
		'no_privileges' => 'Sadece yöneticiler bu sayfaya erişebilir.',
		'no_unapproved_found' => 'No users waiting for approval',
		'not_logged_in' => 'Please ^1log in^2 as the administrator to access this page.',
		'opposite_main_menu' => 'Üst sekmelerin yanında',
		'options' => 'seçenekler',
		'options_reset' => 'Seçenekler sıfırlandı',
		'options_saved' => 'Seçenekler kaydedildi',
		'page_already_used' => 'This is already being used by a page',
		'page_content_html' => 'Sayfa içeriği - HTML kullanabilirsiniz:',
		'page_default_slug' => 'sayfa-^',
		'page_heading' => 'Sayfanın üst kısmında görünecek başlık:',
		'page_name' => 'Name of page (also used for tab or link):',
		'page_slug' => 'Sayfa kısa adı (URL adresindeki adı):',
		'pages_explanation' => 'Click the \'Add Page\' button to add custom content to your Q2A site, or \'Add Link\' to link to any other web page.',
		'pages_title' => 'Sayfalar',
		'pause_mailing_button' => 'Pause Mailing',
		'per_ip_hour' => 'IP başına/saat',
		'per_user_hour' => 'kullanıcı başına/saat',
		'permissions_title' => 'İzinler',
		'permit_to_view' => 'Şu kişiler görebilsin:',
		'php_version' => 'PHP sürümü:',
		'pixels' => 'piksel',
		'plugin_module' => ' (eklenti: ^)',
		'plugin_pages_explanation' => 'Eklenti ile oluşturulan sayfalar:',
		'plugins_title' => 'Eklentiler',
		'points' => 'points',
		'points_defaults_shown' => 'Defaults shown below but NOT YET APPLIED:',
		'points_required' => 'Başlığı hakketmek için gereken puan:',
		'points_title' => 'Puanlar',
		'position' => 'Pozisyon:',
		'posting_title' => 'Gönderim',
		'profile_fields' => 'Kullanıcı sayfaları ve kayıt için ek alanlar:',
		'q2a_build_date' => 'İnşa tarihi:',
		'q2a_db_size' => 'Veritabanı boyutu:',
		'q2a_db_version' => 'Q2A veritabanı sürümü:',
		'q2a_latest_version' => 'En son sürüm:',
		'q2a_version' => 'Question2Answer sürümü:',
		'question_lists' => 'Soru listeleri',
		'question_pages' => 'Soru sayfaları',
		'recalc_categories' => 'Kategorileri yeniden hesapla',
		'recalc_categories_backpaths' => 'Recalculating URL paths for ^1 of ^2 categories...',
		'recalc_categories_complete' => 'All categories were successfully recalculated.',
		'recalc_categories_note' => ' - for post categories and category counts',
		'recalc_categories_recounting' => 'Recounting questions for ^1 of ^2 categories...',
		'recalc_categories_updated' => 'Recalculated for ^1 of ^2 posts...',
		'recalc_points' => 'Kullanıcı puanlarını yeniden hesapla',
		'recalc_points_complete' => 'Tüm kullanıcı puanları başarıyla yeniden hesaplandı.',
		'recalc_points_note' => ' - kullanıcı sıralaması ve puan göstergeleri için',
		'recalc_points_recalced' => 'Recalculated for ^1 of ^2 users...',
		'recalc_points_usercount' => 'Toplam kullanıcı sayısı tahmin ediliyor ...',
		'recalc_posts_count' => 'Toplam soru, cevap ve yorum sayısı alınıyor ...',
		'recalc_stop' => 'Yeniden hesaplamayı durdur',
		'recent_approve_title' => 'Onay bekleyen son içerik',
		'recent_hidden_title' => 'En son gizli gönderiler',
		'recount_posts' => 'Gönderileri yeniden say',
		'recount_posts_as_recounted' => 'Recounted answers and hotness for ^1 of ^2 posts...',
		'recount_posts_complete' => 'All posts were successfully recounted.',
		'recount_posts_note' => ' - the number of answers, votes, flags and hotness for each post',
		'recount_posts_stop' => 'Yeniden saymayı durdur',
		'recount_posts_votes_recounted' => 'Recounted votes and flags for ^1 of ^2 posts...',
		'refill_events' => 'Olay akışını yeniden doldur',
		'refill_events_complete' => 'Tüm olay akışları yeniden dolduruldu',
		'refill_events_note' => ' - kullanıcıların güncelleme listeleri için',
		'refill_events_refilled' => '^1/^2 soru için dolduruldu...',
		'registration_fields' => 'kayıt alanı ekle',
		'reindex_content' => 'İçeriği yeniden indeksle',
		'reindex_content_note' => ' - arama ve ilişkili soru önerileri için',
		'reindex_content_stop' => 'Yeniden indekslemeyi durdur',
		'reindex_pages_reindexed' => '^1/^2 sayfa yeniden indekslendi...',
		'reindex_posts_complete' => 'Tüm mesajlar başarıyla yeniden dizine eklendi.',
		'reindex_posts_reindexed' => '^1/^2 gönderi yeniden indekslendi...',
		'reindex_posts_wordcounted' => '^1/^2 kelime yeniden sayıldı...',
		'requires_php_version' => 'Disabled - requires PHP ^ or later',
		'requires_q2a_version' => 'Disabled - requires Question2Answer ^ or later',
		'reset_options_button' => 'Varsayılanlara sıfırla',
		'reset_options_confirm' => 'Bu sayfadaki seçenekleri varsayılanlarına sıfırlamaya emin misiniz ?',
		'resume_mailing_button' => 'Duyuruyu göndermeye devam et',
		'save_options_button' => 'Seçenekleri Kaydet',
		'save_recalc_button' => 'Kaydet ve Yeniden hesapla',
		'save_view_button' => 'Kaydet ve Gör',
		'send_test_button' => 'Bana Test Maili Gönder',
		'show_defaults_button' => 'Varsayılanları Göster',
		'show_on_register_form' => 'Kayıt formunda şu alanları göster',
		'slug_bad_chars' => 'Kısa isim şu karakterleri içeremez: ^',
		'slug_reserved' => 'Kısa isim başka bir sayfa için ayrılmış',
		'spam_title' => 'Spam',
		'start_mailing_button' => 'Duyuruyu Göndermeye Başla',
		'stats_title' => 'İstatistikler',
		'stop_recalc_warning' => 'Veritabanı temizleme işlemi devam ediyor. Şimdi bu sayfayı kapatırsanız işlemiz iptal edilecektir.',
		'tag_pages' => 'Etiket Sayfaları',
		'tags' => 'Etiketler',
		'tags_and_categories' => 'Etiketler ve Kategoriler',
		'tags_not_shown' => 'Some questions have tags which will not be displayed.',
		'test_sent_to_x' => 'The test message was sent to ^',
		'title_already_used' => 'This value is already being used by another title',
		'top_level_categories' => 'Üst seviye kategoriler:',
		'total_as' => 'Toplam yanıtlar',
		'total_cs' => 'Toplam yorumlar:',
		'total_qs' => 'Toplam sorular:',
		'unnamed_plugin' => 'İsimsiz Eklenti',
		'upgrade_db' => 'Your Question2Answer database needs to be ^1upgraded^2 for this version.',
		'url_format_note' => 'Options with the ^ label are working for your site\'s configuration. For best search engine optimization (SEO), use the first ^ option available.',
		'user_pages' => 'Kullanıcı sayfaları',
		'user_title' => 'Kullanıcı Başlığı - HTML kullanabilirsiniz:',
		'user_titles' => 'Puana dayalı kullanıcı başlıkları:',
		'users_active' => 'Aktif kullanıcılar:',
		'users_must_have' => 'Users must have',
		'users_posted' => 'Gönderi yapmış kullanıcılar:',
		'users_registered' => 'Kayıtlı kullanıcılar:',
		'users_title' => 'Kullanıcılar',
		'users_voted' => 'Oy vermiş kullanıcılar:',
		'version_get_x' => 'get ^',
		'version_latest' => 'en son',
		'version_latest_unknown' => 'bilinmeyen',
		'version_requires_php' => '^1 requires PHP ^2',
		'version_requires_q2a' => '^1 requires Q2A ^2',
		'viewing_title' => 'Görüntüleme',
		'widget_all_pages' => 'Aracı mevcut tüm sayfalarda bu pozisyonda göster',
		'widget_global_options' => ' - ^1seçenekler^2',
		'widget_name' => 'Aracın adı:',
		'widget_no_positions' => 'This widget has already been added to every available position.',
		'widget_not_available' => 'This widget is not available. This could be because the plugin providing the widget is no longer installed.',
		'widget_pages_explanation' => 'Show widget in this position on the following pages:',
		'widgets_explanation' => 'Bulunan araçlar:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
