<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-question.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 Yanıt',
		'a_convert_to_c' => 'Bu yanıtı yoruma çevir',
		'a_convert_to_c_on' => 'Convert this answer into a comment on:',
		'a_convert_warn' => 'Uyarı: Bu çevim işlemi geri alınamaz !',
		'a_convert_warn_cs' => 'Uyarı: Bu dönüşüm işlemi geri alınamaz ve bu yanıtın yorumlarının taşınmasına neden olabilir.',
		'a_notify_email' => 'Yanıtım seçildiğinde ya da yorumlandığında şu adrese mail gönder:',
		'a_notify_label' => 'Yanıtım seçildiğinde ya da yorumlandığında bana mail gönder',
		'a_notify_x_label' => 'Yanıtım seçildiğinde ya da yorumlandığında bana (^) mail gönder',
		'a_waiting_your_approval' => 'Bu yanıt doğrulamanız için bekliyor.',
		'a_your_waiting_approval' => 'Yanıtınız kısa süre içerisinde doğrulanacaktır.',
		'add_answer_button' => 'Yanıtı Gönder',
		'add_comment_button' => 'Yorum ekle',
		'add_q_favorites' => 'Bu soruyu favorilerime ekle',
		'anon_name_label' => 'Görünen adınız (opsiyonel):',
		'answer_button' => 'Yanıtla',
		'answer_limit' => 'Çok fazla yanıt verildi - bir saat sonra tekrar deneyiniz',
		'answer_must_be_approved' => 'Yanıtlamak için hesabınızın onaylanması gerekmektedir.',
		'answer_must_confirm' => 'Bu soruyu yanıtlamak için lütfen ^5e-posta adresini doğrulayın^6.',
		'answer_must_login' => 'Bu soruyu yanıtlamak için lütfen ^1giriş yapın^2 ya da ^3kayıt olun^4.',
		'answer_q_popup' => 'Answer this question',
		'approve_a_popup' => 'Bu soruyu onayla',
		'approve_button' => 'onayla',
		'approve_c_popup' => 'Bu yorumu onayla',
		'approve_q_popup' => 'Bu soruyu onayla',
		'ask_button' => 'Soruyu sor',
		'ask_follow_from_a' => 'Sorunuz şu yanıtla ilişkili olacak:',
		'ask_follow_title' => 'İlişkili soru sor',
		'ask_limit' => 'Çok fazla soru sordunuz. Bir saat sonra tekrar deneyiniz.',
		'ask_must_be_approved' => 'Soru sormak için hesabınızın onaylanması gerekmektedir.',
		'ask_must_confirm' => 'Soru sormak için lütfen ^5e-posta adresini doğrulayın^6.',
		'ask_must_login' => 'Soru sormak için lütfen ^1giriş yapın^2 ya da ^3kayıt olun^4.',
		'ask_same_q' => 'Bu soruyu sormadan önce daha önce cevaplanıp cevaplanmadığını kontrol ediniz:',
		'ask_title' => 'Soru sor',
		'c_notify_email' => 'Benden sonra yorum yapıldığında şu adrese mail gönder:',
		'c_notify_label' => 'Benden sonra yorum yapıldığında bana mail gönder',
		'c_notify_x_label' => 'Benden sonra yorum yapıldığında bana (^) mail gönder',
		'c_waiting_your_approval' => 'Bu yorum onayınızı bekliyor',
		'c_your_waiting_approval' => 'Bu yorum kısa süre içerisinde yorumlanacaktır.',
		'category_ask_not_allowed' => 'Bu kategori içerisinde soru sormanıza izin yok',
		'category_js_note' => 'Kategori seçmek için tarayıcınızda Javascript\'i etkinleştirin.',
		'category_required' => 'Lütfen kategori seçiniz',
		'claim_a_popup' => 'Assign this answer to your user account',
		'claim_button' => 'I wrote this',
		'claim_c_popup' => 'Assign this comment to your user account',
		'claim_q_popup' => 'Assign this question to your user account',
		'clear_flags_button' => 'işaretlemeleri temizle',
		'clear_flags_popup' => 'Tüm kullanıcılar tarafından yapılmış işaretlemeleri temizle',
		'close_button' => 'kilitle',
		'close_duplicate' => 'Bu başka bir sorunun tekrarı',
		'close_duplicate_error' => 'Tekrarlayan soru bulunamadı - lütfen başka bir soru numarası deneyiniz. Örneğin: 123.',
		'close_form_button' => 'Soruyu kilitle',
		'close_form_title' => 'Bu soruyu kilitle',
		'close_original_note' => 'Bunun dışında URL adresindeki soru numarasını da yazabilirsiniz. Örneğin: 123',
		'close_original_title' => 'Orjinal sorunun URL adresi:',
		'close_q_popup' => 'Bu souruyu yeni yanıtlara kapat',
		'close_reason_title' => 'Bu soruyu kilitleme sebebiniz:',
		'closed_as_duplicate' => 'tekrarlayan soru:',
		'closed_with_note' => 'Sorunun kilitlenme sebebi:',
		'comment_a_popup' => 'Bu yanıta yorum yap',
		'comment_button' => 'yorum yap',
		'comment_limit' => 'Çok fazla yorum yapıldı - lütfen bir saat sonra tekrar deneyiniz',
		'comment_must_be_approved' => 'Yorum yapabilmeniz için hesabınızın onaylanmış olması gerekmektedir.',
		'comment_must_confirm' => 'Yorum eklemek için lütfen ^5e-posta adresinizi doğrulayınız^6.',
		'comment_must_login' => 'Yorum yapmak için lütfen ^1giriş yapınız^2 ya da ^3kayıt olunuz^4.',
		'comment_on_a' => 'On answer: ',
		'comment_on_q' => 'On question: ',
		'comment_q_popup' => 'Bu soruya yorum ekle',
		'delete_a_popup' => 'Bu yanıtı kalıcı olarak silin',
		'delete_button' => 'sil',
		'delete_c_popup' => 'Bu yorumu kalıcı olarak silin',
		'delete_q_popup' => 'Bu soruyu kalıcı olarak silin',
		'duplicate_content' => 'Gönderiniz tekrar gibi görünüyor.',
		'edit_a_popup' => 'Bu yanıtı düzenle',
		'edit_a_title' => 'Yanıtı düzenle',
		'edit_button' => 'düzenle',
		'edit_c_popup' => 'Bu yorumu düzenle',
		'edit_c_title' => 'Yorumu düzenle',
		'edit_must_confirm' => 'Düzenleme yapmak için lütfen ^5e-posta adresinizi doğrulayınız^6.',
		'edit_must_login' => 'Düzenleme yapmak için lütfen ^1giriş yapınız^2 ya da ^3kayıt olunuz^4',
		'edit_q_popup' => 'Bu soruyu düzenle',
		'edit_q_title' => 'Soruyu düzenle',
		'example_tags' => 'Örnek etiketler: ',
		'flag_a_popup' => 'Bu yanıtı spam veya uygunsuz olarak işaretle',
		'flag_button' => 'işaretle',
		'flag_c_popup' => 'Bu yorumu spam veya uygunsuz olarak işaretle',
		'flag_hide_button' => 'işaretle ve gizle',
		'flag_limit' => 'Çok fazla gönderi işaretlendi - lütfen bir saat sonra tekrar deneyiniz',
		'flag_must_confirm' => 'İşaretleme yapmak için lütfen ^5e-posta adresinizi doğrulayınız^6.',
		'flag_must_login' => 'İşaretleme yapmak için lütfen ^1giriş yapınız^2 ya da ^3kayıt olunuz^4',
		'flag_not_allowed' => 'Bu işaretlenemez',
		'flag_q_popup' => 'Bu soruyu spam veya uygunsuz olarak işaretle',
		'follow_a_popup' => 'Bu yanıtla alakalı yeni soru sor',
		'follow_button' => 'ilişkili soru sor',
		'follows_a' => 'Şu sorunun yanıtıyla ilişkili:',
		'follows_q' => 'soru ile ilgili:',
		'hide_a_popup' => 'Bu yanıtı gizle',
		'hide_button' => 'gizle',
		'hide_c_popup' => 'Bu yorumu gizle',
		'hide_q_popup' => 'Bu soruyu gizle',
		'matching_tags' => 'Eşleşen etiketler: ',
		'max_tags_x' => 'Maksimum: ^ etikete izin veriliyor',
		'min_tags_x' => 'En az ^ etiket girmelisiniz',
		'notify_email_note' => 'E-posta adresiniz size bildirim göndermek dışında kullanılmayacaktır.',
		'q_category_label' => 'Kategori:',
		'q_content_label' => 'Soru hakkında detaylı bilgi :',
		'q_hidden_author' => 'Bu soru sorulan tarafından gizlenmiştir',
		'q_hidden_flagged' => 'Bu soru işaretlenmiş ve gizlenmiştir',
		'q_hidden_other' => 'Bu soru gizlenmiş',
		'q_notify_email' => 'Bu soru yanıtlandığında ya da yorumlandığında şu adrese mail gönder:',
		'q_notify_label' => 'Bu soru yanıtlandığında ya da yorumlandığında bana mail gönder',
		'q_notify_x_label' => 'Bu soru yanıtlandığında ya da yorumlandığında bana (^) mail gönder',
		'q_tags_comma_label' => 'Etiketler - ayraç olarak virgül (,) kullanın:',
		'q_tags_label' => 'Etiketler - kelimeleri birleştirmek için tire (-) kullanınız:',
		'q_title_label' => 'Sorunuzun başlığı:',
		'q_waiting_approval' => 'Bu soru onay için beklemektedir',
		'q_waiting_your_approval' => 'Bu soru onayınızı beklemektedir',
		'q_your_waiting_approval' => 'Sorunuz incelenecek ve kısa sürede onaylanacaktır',
		'recat_button' => 'yeniden kategorilendir',
		'recat_popup' => 'Sorunun kategorisini değiştir',
		'recat_q_title' => 'Soruyu yeniden kategorilendir',
		'reject_a_popup' => 'Yanıtı reddet',
		'reject_button' => 'reddet',
		'reject_c_popup' => 'Bu yorumu reddet',
		'reject_q_popup' => 'Bu soruyu reddet',
		'remove_q_favorites' => 'Bu soruyu favorilerimden kaldır',
		'reopen_button' => 'yeniden aç',
		'reopen_q_popup' => 'Bu soruyu yeniden aç',
		'reply_button' => 'yanıtla',
		'reply_c_popup' => 'Bu yorumu yanıtla',
		'reshow_a_popup' => 'Bu yanıtı yeniden göster',
		'reshow_button' => 'yeniden göster',
		'reshow_c_popup' => 'Bu yorumu yeniden göster',
		'reshow_q_popup' => 'Bu soruyu yeniden göster',
		'retag_button' => 'yeniden etiketle',
		'retag_cat_popup' => 'Bu sorunun kategorisini veya etiketlerini değiştirin',
		'retag_popup' => 'Bu sorunun etiletlerini değiştirin',
		'retag_q_title' => 'Soruyu yeniden etiketle',
		'save_silent_label' => 'Düzenlendiği belli olmaması için gizli düzenle',
		'select_popup' => 'En iyi cevap olarak seçmek için tıklayınız',
		'select_text' => 'En iyi cevap',
		'show_1_comment' => '1 yorumu göster',
		'show_1_previous_comment' => '1 geçmiş yorumu göster',
		'show_x_comments' => '^ yorumu göster',
		'show_x_previous_comments' => '^ geçmiş yorumu göster',
		'unflag_button' => 'işareti kaldır',
		'unflag_popup' => 'Eklediğiniz işareti kaldırınpp',
		'unselect_popup' => 'Seçimi kaldırmak için tıklayınız',
		'x_answers_title' => '^ Yanıt',
		'your_answer_title' => 'Yanıtınız',
		'your_comment_a' => 'Bu cevaba yorumunuz:',
		'your_comment_q' => 'Bu soruya yorumunuz:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
