<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-options.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => 'Gönderiye sahip kullanıcıların kullanıcı adlarını değiştirebilmelerine izin ver:',
		'allow_close_questions' => 'Soruların elle kilitlenmesine izin ver:',
		'allow_login_email_only' => 'Sadece e-posta adresiyle giriş yap (kullanıcı adıyla değil):',
		'allow_multi_answers' => 'Kullanıcıya ait birden fazla yanıta izin ver:',
		'allow_no_category' => 'Kategorisiz sorulara izin ver',
		'allow_no_sub_category' => 'Kategorisi olan fakat alt kategorisi olmayan sorulara izin ver',
		'allow_private_messages' => 'Kullanıcılar arasında  özel mesajlaşmayı etkinleştir:',
		'allow_self_answer' => 'Kullanıcıların kendi sorularını yanıtlamasına izin ver:',
		'allow_user_walls' => 'Kullanıcı profillerinde duvar yazılarını etkinleştir:',
		'allow_view_q_bots' => 'Allow search engines to view question pages',
		'approve_user_required' => 'All new users must be approved:',
		'avatar_allow_gravatar' => '^1Gravatar^2 avatarlarına izin ver:',
		'avatar_allow_upload' => 'Kullanıcıların avatar yüklemelerine izin ver:',
		'avatar_default_show' => 'Varsayılan avatar:',
		'avatar_message_list_size' => 'Mesaj listelerindeki avatar boyutu:',
		'avatar_profile_size' => 'Profil sayfasındaki avatar boyutu:',
		'avatar_q_list_size' => 'Soru listelerindeki avatar boyutu :',
		'avatar_q_page_a_size' => 'Yanıtlardaki avatar boyutu:',
		'avatar_q_page_c_size' => 'Yorumlardaki avatar boyutu:',
		'avatar_q_page_q_size' => 'Sorulardaki avatar boyutu:',
		'avatar_store_size' => 'Avatarları saklamak için maksimum boyut:',
		'avatar_users_size' => 'En çok puana sahip kullanıcılar sayfasındaki avatar boyutu:',
		'block_bad_words' => 'Sansürlü kelimeler - kelimeleri virgül ya da boşluk ile ayırınız:',
		'block_ips_write' => 'Engellenmiş IP adresleri - virgül ya da boşluk ile ayırınız:',
		'captcha_module' => 'Şu captcha modülünü kullan:',
		'captcha_on_anon_post' => 'Anonim kullanıcılar için captcha kullan:',
		'captcha_on_feedback' => 'Geri bildirim formu için captcha kullan:',
		'captcha_on_register' => 'Kullanıcı kayıtları için captcha kullan:',
		'captcha_on_reset_password' => 'Şifre sıfırlama formu için captcha kullan:',
		'captcha_on_unapproved' => 'Kullanıcı onaylanmadıysa captcha kullan:',
		'captcha_on_unconfirmed' => 'E-posta adresi doğrulanmadıysa captcha kullan:',
		'columns_tags' => 'Columns on Tags page:',
		'columns_users' => 'Columns on Users page:',
		'comment_on_as' => 'Cevaplarda yorumlara izin ver:',
		'comment_on_qs' => 'Sorularda yorumlara izin ver:',
		'confirm_user_emails' => 'E-posta onaylama isteği gönder:',
		'confirm_user_required' => 'Tüm yeni kullanıcılar e-posta adresini doğrulamalıdır:',
		'custom_home_content' => 'Ana sayfa içeriği - HTML kullanabilirsiniz:',
		'custom_home_heading' => 'Ana sayfa başlığı:',
		'default_privacy' => 'Gizlilik: E-posta adresiniz üçüncü kişilerle paylaşılmayacaktır.',
		'default_sidebar' => '^\'a hoşgeldiniz. Burada soru sorabilir ve diğer kullanıcıların sorularını yanıtlayabilirsiniz.',
		'default_subject' => '^\'dan yeni duyuru',
		'default_suffix' => 'Forum',
		'default_terms' => 'I agree to the ^ Terms & Conditions and Privacy Policy',
		'do_ask_check_qs' => 'Soru formunda ilişkili soruları göster:',
		'do_close_on_select' => 'Soruları şu yanıtla kilitle:',
		'do_complete_tags' => 'Show matching tags while typing:',
		'do_count_q_views' => 'Soru görüntülenme sayısını kaydet:',
		'do_example_tags' => 'Show example tags based on question:',
		'editor_for_as' => 'Yanıtlar için varsayılan editör:',
		'editor_for_cs' => 'Yorumlar için varsayılan editör:',
		'editor_for_qs' => 'Sorular için varsayılan editör:',
		'email_privacy' => 'E-posta adresleri için gizlilik bildirimi - HTML kullanılabilir',
		'extra_field_active' => 'Daha fazla bilgi için soru formunda ek alan:',
		'extra_field_display' => 'Show the extra information on question pages',
		'extra_field_display_label' => 'Show the extra information on question pages with label:',
		'feed_for_activity' => 'Son etkinlikler için besleme:',
		'feed_for_hot' => 'Sıcak sorular için besleme:',
		'feed_for_qa' => 'Son sorular ve cevaplar için besleme:',
		'feed_for_questions' => 'Son sorulan sorular için besleme',
		'feed_for_search' => 'Arama sonuçları için besleme:',
		'feed_for_tag_qs' => 'Tüm etiketler için besleme:',
		'feed_for_unanswered' => 'Cevaplanmamış sorular için besleme:',
		'feed_full_text' => 'Beslemeler içinde tam metin göster:',
		'feed_number_items' => 'Maksimum besleme uzunluğu:',
		'feed_per_category' => 'Kategori tekil beslemeleri için maksimum uzunluk:',
		'feedback_email' => 'Yönetici mesajları için e-posta adresi (kullanıcılara gözükmez)',
		'feedback_enabled' => 'Geri bildirim için bir sayfa göster',
		'flagging_hide_after' => 'Şu kadar işaretlenme aldığında gönderiyi otomatik olarak gizle:',
		'flagging_notify_every' => 'Gönderi her şu kadar daha işaretlenme aldıkça bana mail gönder:',
		'flagging_notify_first' => 'Gönderi şu kadar işaretlenme alırsa bana mail gönder:',
		'flagging_of_posts' => 'Gönderilerin işaretlenmesine izin ver:',
		'follow_on_as' => 'Cevaplarla ilişkili soruların sorulabilmesine izin ver:',
		'from_email' => 'Bildirimler için gönderim adresi:',
		'hot_weight_a_age' => 'Soru yeni yanıta sahip:',
		'hot_weight_answers' => 'Soru bir çok cevaba sahip:',
		'hot_weight_q_age' => 'Soru yeni:',
		'hot_weight_views' => 'Soru çok görüntülenmiş:',
		'hot_weight_votes' => 'Soru bir çok pozitif yanıta sahip:',
		'links_in_new_window' => 'Bağlantıları yeni sekmede aç:',
		'logo_height' => 'Logo yüksekliği:',
		'logo_show' => 'Sayfa üstbaşlığında logo göster',
		'logo_url' => 'Logonun URL adresi - Absolute ya da relative yol kullanılabilir :',
		'logo_width' => 'Logo genişliği:',
		'mailing_body' => 'Gövde metni:',
		'mailing_enabled' => 'Kullanıcılara duyuru göndermeyi etkinleştir',
		'mailing_from_email' => 'Gelen kutusunda görünecek e-posta adresi:',
		'mailing_from_name' => 'Gelen kutusunda görünecek isim:',
		'mailing_per_minute' => 'Mail oranı:',
		'mailing_subject' => 'Konu:',
		'match_1' => 'En dar',
		'match_2' => 'Dar',
		'match_3' => 'Varsayılan',
		'match_4' => 'Geniş',
		'match_5' => 'En geniş',
		'match_ask_check_qs' => 'Benzer soru eşleşmesi:',
		'match_example_tags' => 'Example tags matching:',
		'match_related_qs' => 'Related questions matching:',
		'max_len_q_title' => 'Maksimum soru başlığı uzunluğu:',
		'max_num_q_tags' => 'Maksimum etiket sayısı:',
		'max_rate_ip_as' => 'Yanıtlama sınırı oranı:',
		'max_rate_ip_cs' => 'Yorum yapma sınırı oranı:',
		'max_rate_ip_flags' => 'Göderi işaretleme sınırı oranı:',
		'max_rate_ip_logins' => 'Giriş yapma sınırı oranı:',
		'max_rate_ip_messages' => 'Özel mesaj gönderme ve duvar yazısı yazma sınırı oranı:',
		'max_rate_ip_qs' => 'Soru sorma sınırı oranı:',
		'max_rate_ip_registers' => 'Üye kayıt sınırı oranı:',
		'max_rate_ip_uploads' => 'Dosya yükleme sınırı oranı:',
		'max_rate_ip_votes' => 'Oylama sınırı oranı:',
		'max_rate_user_as' => 'Maximum answers per user per hour:',
		'max_rate_user_cs' => 'Maximum comments per user per hour:',
		'max_rate_user_flags' => 'Maximum flags per user per hour:',
		'max_rate_user_messages' => 'Maximum private messages per user per hour:',
		'max_rate_user_qs' => 'Maximum questions per user per hour:',
		'max_rate_user_uploads' => 'Maximum uploads per user per hour:',
		'max_rate_user_votes' => 'Maximum votes per user per hour:',
		'min_len_a_content' => 'Minimum cevap uzunluğu:',
		'min_len_c_content' => 'Minimum yorum uzunluğu:',
		'min_len_q_content' => 'Minimum soru uzunluğu:',
		'min_len_q_title' => 'Minimum soru başlığı uzunluk:',
		'min_num_q_tags' => 'Minimum etiket sayısı:',
		'moderate_anon_post' => 'Anonim gönderiler için moderasyon kullan:',
		'moderate_by_points' => 'Az puana sahip kullanıcılar için moderasyon kullan:',
		'moderate_edited_again' => 'Düzenleme sonrası tekrar moderasyon iste:',
		'moderate_notify_admin' => 'Gönderi moderasyon istediğinde bana gönder:',
		'moderate_points_limit' => 'Şu puandan az kullanıcıları moderasyona tabi tut:',
		'moderate_unapproved' => 'Kullanıcı henüz onaylanmadıysa moderasyon kullan:',
		'moderate_unconfirmed' => 'E-posta onaylanmadıysa moderasyon kullan:',
		'moderate_update_time' => 'Moderasyona tabi gönderilerde gösterilecek zaman:',
		'moderate_users' => 'Kullanıcı moderasyonunu (onayını) etkinleştir:',
		'neat_urls' => 'URL yapısı:',
		'notify_admin_q_post' => 'Soru gönderildiğinde bu adrese mail gönder',
		'notify_users_default' => 'E-posta bildirimi kutusu işaretli gelsin:',
		'option_default' => 'Varsayılan',
		'page_size_activity' => 'Tüm Etkinlikler sayfasının uzunluğu:',
		'page_size_ask_check_qs' => 'Gösterilecek maksimum benzer soru sayısı:',
		'page_size_ask_tags' => 'Maximum tag hints to show:',
		'page_size_home' => 'Soru cevap sayfasının uzunluğu:',
		'page_size_hot_qs' => 'Sıcak sıcak! sayfasının uzunluğu:',
		'page_size_pms' => 'Sayfa başına özel mesaj sayısı:',
		'page_size_q_as' => 'Sayfa başına yanıt sayısı:',
		'page_size_qs' => 'Sorular sayfasının uzunluğu:',
		'page_size_related_qs' => 'Maksimum ilişkili soru sayısı:',
		'page_size_search' => 'Sayfa başına arama sonucı:',
		'page_size_tag_qs' => 'Questions on each tag page:',
		'page_size_tags' => 'Etiketler sayfasının uzunluğu:',
		'page_size_una_qs' => 'Yanıtlanmamış sayfasının uzunluğu:',
		'page_size_users' => 'Kullanıcılar sayfasının uzunluğu:',
		'page_size_wall' => 'Sayfa başına duvar yazısı:',
		'pages_prev_next' => 'Önceki/Sonraki sayfalara bağlantı ver:',
		'permit_admins' => 'Yöneticiler',
		'permit_all' => 'Herkes',
		'permit_approve_users' => 'Kayıtlı kullanıcıları onaylama:',
		'permit_approved' => 'Sadece onaylanmış kullanıcılar',
		'permit_approved_points' => 'Yeterli puana sahip onaylı kullanıcılar',
		'permit_block' => 'Kullanıcıları ve IP adreslerini engelleme ve bunların engellerini kaldırma:',
		'permit_confirmed' => 'E-posta adresi onaylanmış kayıtlı kullanıcılar',
		'permit_create_admins' => 'Yönetici ekleme:',
		'permit_create_eds_mods' => 'Editör ve moderatör ekleme:',
		'permit_create_experts' => 'Uzman ekleme:',
		'permit_delete_users' => 'Kullanıcıları silme:',
		'permit_editors' => 'Editörler, Moderatörler, Yöneticiler',
		'permit_experts' => 'Uzmanlar, Editörler, Moderatörler, Yöneticiler',
		'permit_moderators' => 'Yöneticiler ve Moderatörler',
		'permit_points' => 'Yeterli puana sahip kayıtlı kullanıcılar',
		'permit_points_confirmed' => 'Onaylanmış e-posta adresine sahip ve yeterli puana sahip kullanıcılar',
		'permit_see_emails' => 'Kullanıcı e-posta adreslerini görme:',
		'permit_supers' => 'Süper Yöneticiler',
		'permit_users' => 'Kayıtlı kullanıcılar',
		'place_full_below_content' => 'Tam genişlik - İçerik altında',
		'place_full_below_footer' => 'Tam genişlik - Alt başlık altında',
		'place_full_below_nav' => 'Tam genişlik - Menü altında',
		'place_full_top' => 'Tam genişlik - Sayfa üstünde',
		'place_main_below_lists' => 'İçerik alanı - Listelerin altında',
		'place_main_below_title' => 'İçerik alanı - Başlık altında',
		'place_main_bottom' => 'İçerik alanı - Alt kısımda',
		'place_main_top' => 'İçerik alanı - Üst kısımda',
		'place_side_below_categories' => 'Yan panel - Kategoriler altında',
		'place_side_below_sidebar' => 'Yan panel - Yan kutu altında',
		'place_side_last' => 'Yan panel - En sonda',
		'place_side_top' => 'Yan panel - Üst kısımda',
		'points_a_selected' => 'Yanıtınız en iyi cevap seçildiğinde:',
		'points_a_voted_max_gain' => 'Her yanıt için kullanabileceği pozitif oy sınırı:',
		'points_a_voted_max_loss' => 'Her yanıt için kullanabileceği nrgatif oy sınırı:',
		'points_base' => 'Hoşgeldin bonusu:',
		'points_multiple' => 'Puan çarpanı:',
		'points_per_a_voted_down' => 'Kendi cevabına negatif oy verildiğinde:',
		'points_per_a_voted_up' => 'Kendi cevabına pozitif oy verildiğinde:',
		'points_per_q_voted_down' => 'Kendi sorusuna negatif oy verildiğinde:',
		'points_per_q_voted_up' => 'Kendi sorusuna pozitif oy verildiğinde:',
		'points_post_a' => 'Yanıt gönderdiğinde:',
		'points_post_q' => 'Soru sorduğunda:',
		'points_q_voted_max_gain' => 'Her soru için kullanabileceği pozitif oy sınırı:',
		'points_q_voted_max_loss' => 'Her soru için kullanabileceği negatif oy sınırı:',
		'points_select_a' => 'Selecting an answer for your question:',
		'points_vote_down_a' => 'Bir yanıtı negatif oyladığında:',
		'points_vote_down_q' => 'Bir soruyu negatif oyladığında:',
		'points_vote_up_a' => 'Bir yanıtı pozitif oyladığında :',
		'points_vote_up_q' => 'Bir soruyu pozitif oyladığında:',
		'q_urls_remove_accents' => 'Soru URL adresleri içerisindeki fonetik harfleri kaldır:',
		'q_urls_title_length' => 'URL adresi içerisindeki soru başlığı uzunluğu:',
		'register_notify_admin' => 'Yeni kullanıcı kayıt olduğunda bana mail at:',
		'search_module' => 'Şu arama modülünü kullan:',
		'show_a_form_immediate' => 'Soru sayfasında cevap formunu göster:',
		'show_always' => 'Her zaman',
		'show_c_reply_buttons' => 'Yorumların üzerinde yanıtla butonu göster:',
		'show_custom_answer' => 'Cevap formu üzerinde özel mesaj - HTML kullanabilirsiniz:',
		'show_custom_ask' => 'Soru formu üzerinde özel mesaj - HTML kullanabilirsiniz:',
		'show_custom_comment' => 'Yorum formu üzerinde özel mesaj - HTML kullanabilirsiniz:',
		'show_custom_footer' => 'Tüm sayfaların altında görünen isteğe bağlı HTML:',
		'show_custom_header' => 'Tüm sayfaların üstünde görünen isteğe bağlı HTML:',
		'show_custom_home' => 'Özel anasayfa içeriği HTML\'i:',
		'show_custom_in_head' => 'Tüm sayfaların <head> bölümünde bulunacak HTML:',
		'show_custom_register' => 'Kayıt formunda özel mesaj - HTML kullanabilirsiniz:',
		'show_custom_sidebar' => 'Tüm sayfalarda görünen isteğe bağlı yan kutu HTML\'i:',
		'show_custom_sidepanel' => 'Tüm sayfalarda görünen isteğe bağlı yan panel HTML\'i:',
		'show_custom_welcome' => 'Kayıt e-postasında özel mesaj - HTML kullanabilirsiniz:',
		'show_fewer_cs_count' => 'Yorumlar kısmen gizliyse en son şu kadar göster:',
		'show_fewer_cs_from' => 'Partially hide comments if more than:',
		'show_full_date_days' => 'Şu kadar sonra tam tarihi göster:',
		'show_home_description' => 'Anasayfa için <meta> bölümü içeriği:',
		'show_if_no_as' => 'Henüz yanıtlanmamışsa',
		'show_message_history' => 'Özel mesaj geçmişini depola ve göster:',
		'show_never' => 'Hiçbir zaman',
		'show_notice_visitor' => 'İlk defa gelen kullanıcıları üst kısımda bilgilendir - HTML kullanabilirsiniz',
		'show_notice_welcome' => 'Yeni kayıt olmuş kullanıcıları bilgilendir - HTML kullanabilirsiniz:',
		'show_post_update_meta' => 'Güncellemeleri gönderi metasında göster:',
		'show_register_terms' => 'Kayıt formundaki kullanım koşulları onay kutusu - HTML kullanabilirsiniz:',
		'show_selected_first' => 'Seçilmiş yanıtları üste taşı:',
		'show_url_links' => 'Gönderilerde URL adreslerini tanımla ve bağlantı olarak göster:',
		'show_user_points' => 'Kullanıcı puanlarını göster:',
		'show_user_titles' => 'Kullanıcı başlıklarını göster:',
		'show_view_count_q_page' => 'Soru sayfalarında görüntülenme sayısını göster:',
		'show_view_counts' => 'Soru listelerinde görüntülenme sayısını göster:',
		'show_when_created' => 'Kullanıcı gönderilerinin yaşını göster:',
		'site_language' => 'Site dili:',
		'site_maintenance' => 'Bakım modu',
		'site_text_direction' => 'Yazı yönü:',
		'site_theme' => 'Tema:',
		'site_theme_mobile' => 'Mobil aygıtlar için tema:',
		'site_title' => 'Sitesi adı:',
		'site_url' => 'Tercih edilen URL adresi:',
		'smtp_active' => 'Yerel mail sunucusu yerine SMTP ile mail gönder',
		'smtp_address' => 'SMTP sunucu adresi:',
		'smtp_authenticate' => 'SMTP kullanıcı adı ve şifresi kullan',
		'smtp_password' => 'SMTP şifresi:',
		'smtp_port' => 'SMTP sunucu portu:',
		'smtp_secure' => 'Güvenli SMTP bağlantısı:',
		'smtp_secure_none' => 'Hiçbiri',
		'smtp_username' => 'SMTP kullanıcı adı:',
		'sort_answers_by' => 'Cevapları şuna göre sırala:',
		'sort_time' => 'Zaman',
		'sort_votes' => 'Oy',
		'suspend_register_users' => 'Geçici olarak yeni kayıtları durdur:',
		'tag_separator_comma' => 'Etiket ayracı olarak sadece virgül kullan:',
		'tags_or_categories' => 'Soru sınıflandırması:',
		'time_approved' => 'Onaylandığı zaman',
		'time_written' => 'Gönderildiği zaman',
		'votes_separated' => 'Pozitif ve negatif yorumları ayrı göster:',
		'voting_on_as' => 'Cevapları oylamaya izin ver:',
		'voting_on_q_page_only' => 'Sadece soru sayfası içerisinde oylamaya izin ver:',
		'voting_on_qs' => 'Soruları oylamaya izin ver:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
