<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-main.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 yanıt',
		'1_comment' => '1 yorum',
		'1_day' => '1 gün',
		'1_disliked' => '1 beğenmeme',
		'1_flag' => '1 işaretlenme',
		'1_hour' => '1 saat',
		'1_liked' => '1 beğenme',
		'1_minute' => '1 dakika',
		'1_month' => '1 ay',
		'1_point' => '1 puan',
		'1_question' => '1 soru',
		'1_second' => '1 saniye',
		'1_tag' => '1 etiket',
		'1_user' => '1 kullanıcı',
		'1_view' => '1 görünme',
		'1_vote' => '1 oy',
		'1_week' => '1 hafta',
		'1_year' => '1 yıl',
		'add_category_x_favorites' => '^ kategorisini favorilerime ekle',
		'add_favorites' => 'Favorilerime ekle',
		'add_tag_x_favorites' => '^ etiketini favorilerime ekle',
		'all_categories' => 'Tüm kategoriler',
		'anonymous' => 'anonim',
		'answer_edited' => 'yanıt düzenlendi',
		'answer_reshown' => 'yanıt yeniden gösterildi',
		'answer_selected' => 'yanıt seçildi',
		'answered' => 'yanıtlandı',
		'answered_qs_in_x' => '^ içerisindeki en çok yanıtlanan sorular',
		'answered_qs_title' => 'En çok yanıtlanan sorular',
		'asked' => 'soruldu',
		'asked_related_q' => 'ilişkili soru sordu',
		'by_x' => '^ tarafından',
		'cancel_button' => 'İptal',
		'closed' => 'kilitlendi',
		'comment_edited' => 'yorum düzenlendi',
		'comment_moved' => 'yorum taşındı',
		'comment_reshown' => 'yorum yeniden gösterildi',
		'commented' => 'yorumlandı',
		'date_day_min_digits' => 2, // 1 or 2
		'date_format_other_years' => '^day ^month, ^year',
		'date_format_this_year' => '^day ^month',
		'date_month_1' => 'Ocak',
		'date_month_2' => 'Şubat',
		'date_month_3' => 'Mart',
		'date_month_4' => 'Nisan',
		'date_month_5' => 'Mayıs',
		'date_month_6' => 'Haziran',
		'date_month_7' => 'Temmuz',
		'date_month_8' => 'Ağustos',
		'date_month_9' => 'Eylül',
		'date_month_10' => 'Ekim',
		'date_month_11' => 'Kasım',
		'date_month_12' => 'Aralık',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'düzenlendi',
		'email_error' => 'E-posta gönderilmeye çalışılırken hata oluştu.',
		'field_required' => 'Lütfen bu alanı boş bırakmayınız',
		'file_upload_limit_exceeded' => 'Dosya boyutu sunucu konfigürasyonunda belirtilen değerden büyük.',
		'general_error' => 'Sunucu hatası oluştu. Lütfen tekrar deneyiniz.',
		'hidden' => 'gizli',
		'highest_users' => 'En çok puana sahip kullanıcılar',
		'hot_qs_in_x' => '^ içerisindeki sıcak sorular',
		'hot_qs_title' => 'Sıcak sorular',
		'image_not_read' => 'Bu resim okunamadı. Lütfen şu uzantılardan birini deneyiniz: ^',
		'image_too_big_x_pc' => 'Resim çok büyük ^% boyutunda ölçekleyiniz.',
		'in_category_x' => '^ içerisinde',
		'ip_address_x' => 'IP adresi ^',
		'logged_in_x' => 'Merhaba ^',
		'max_length_x' => 'Maksimum uzunluk: ^ karakter',
		'max_upload_size_x' => 'Maksimum yükleme boyutu: ^',
		'me' => 'Ben',
		'meta_order' => 'who^^when^where^what', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Lütfen biraz daha açıklayıcı olun. En az ^ karakter girebilirsiniz',
		'moved' => 'taşındı',
		'nav_activity' => 'Tüm Etkinlikler',
		'nav_admin' => 'Yönetici',
		'nav_ask' => 'Soru sor',
		'nav_categories' => 'Kategoriler',
		'nav_feedback' => 'Geri bildirim gönder',
		'nav_home' => 'Anasayfa',
		'nav_hot' => 'Sıcak sıcak!',
		'nav_login' => 'Giriş',
		'nav_logout' => 'Çıkış',
		'nav_most_answers' => 'En çok yanıtlananlar',
		'nav_most_recent' => 'En son',
		'nav_most_views' => 'En çok görüntülenenler',
		'nav_most_votes' => 'En çok oylananlar',
		'nav_no_answer' => 'Yanıtsızlar',
		'nav_no_selected_answer' => 'Seçilmiş yanıt olmayan',
		'nav_no_upvoted_answer' => 'Pozitif oylanmış yanıt olmayan',
		'nav_qa' => 'Forum',
		'nav_qs' => 'Sorular',
		'nav_register' => 'Kayıt',
		'nav_tags' => 'Etiketler',
		'nav_unanswered' => 'Yanıtlanmamış',
		'nav_updates' => 'Güncellemelerim',
		'nav_users' => 'Kullanıcılar',
		'no_active_users' => 'Aktif kullanıcı bulunamadı',
		'no_answers_found' => 'Hiç yanıt bulunamadı',
		'no_answers_in_x' => '^ içerisinde hiç yanıt bulunamadı',
		'no_categories_found' => 'Hiç kategori bulunamadı',
		'no_category' => 'Kategori yok',
		'no_comments_found' => 'Hiç yorum bulunamadı',
		'no_comments_in_x' => '^ içerisinde hiç yanıt bulunamadı',
		'no_questions_found' => 'Hiç soru bulunamadı',
		'no_questions_in_x' => '^ içerisinde hiç soru bulunamadı',
		'no_related_qs_title' => 'Alakalı soru bulunamadı',
		'no_results_for_x' => '^ için sonuç bulunamadı',
		'no_tags_found' => 'Hiç etiket bulunamadı',
		'no_una_questions_found' => 'Hiç yanıtlanmamış soru bulunamadı',
		'no_una_questions_in_x' => '^ içerisinde hiç yanıtlanmamış soru bulunamadı',
		'no_unselected_qs_found' => 'Seçilmiş yanıt bulunan hiç soru bulunamadı',
		'no_unupvoteda_qs_found' => 'Pozitif oylanmış yanıt içermeyen hiç soru bulunamadı',
		'page_label' => 'Sayfa:',
		'page_next' => 'ileri',
		'page_not_found' => 'Sayfa bulunamadı',
		'page_prev' => 'geri',
		'popular_tags' => 'En popüler etiketler',
		'questions_tagged_x' => '^ olarak etiketlenen en son sorular',
		'recategorized' => 'yeniden kategorize edilmiş',
		'recent_activity_in_x' => '^ içerisindeki son etkinlikler',
		'recent_activity_title' => 'Son etkinlikler',
		'recent_as_in_x' => '^ içerisindeki son yanıtlanan sorular',
		'recent_as_title' => 'Son yanıtlanan sorular',
		'recent_cs_in_x' => '^ içerisindeki son yorumlanan sorular',
		'recent_cs_title' => 'Son yorumlanan sorular',
		'recent_qs_as_in_x' => '^ içerisindeki son sorular ve yanıtları',
		'recent_qs_as_title' => 'Son sorular ve yanıtlar',
		'recent_qs_in_x' => '^ içerisindeki son sorular ',
		'recent_qs_title' => 'Son sorular',
		'related_qs_title' => 'İlgili sorular',
		'remove_favorites' => 'Favorilerimden kaldır',
		'remove_x_favorites' => 'Favorilerimden kaldır: ^ ',
		'reopened' => 'yeniden açıldı',
		'reshown' => 'yeniden gösterildi',
		'results_for_x' => '"^" için arama sonuçları',
		'retagged' => 'yeniden etiketlendi',
		'save_button' => 'Değişiklikleri Kaydet',
		'search_button' => 'Ara',
		'search_explanation' => 'Arama kutusuna bir şeyler yazıp tekrar deneyin.',
		'search_title' => 'Arama sonuçları',
		'selected' => 'seçildi',
		'send_button' => 'Gönder',
		'since_x' => '^ beri',
		'suggest_ask' => 'Aklına bir şey mi takıldı ? ^1Bize sorarak^2 cevabını bul.',
		'suggest_category_qs' => 'Daha fazla görmek için, ^1kategorideki tüm sorular^2a tıklayınız.',
		'suggest_qs' => 'Daha fazla görmek için, ^1Sorular^2 sayfasına gidin.',
		'suggest_qs_tags' => 'Daha fazla görmek için, ^1tüm sorular^2 ya da ^3popüler etiketler^4e tıklayınız.',
		'to_x' => '^e',
		'unanswered_qs_in_x' => '^ içerisindeki yanıtlanmamış sorular',
		'unanswered_qs_title' => 'En son yanıtlanmamış sorular',
		'unselected_qs_in_x' => '^ içerisindeki seçilmiş yanıt bulunmayan sorular',
		'unselected_qs_title' => 'Seçilmiş yanıt bulunmayan son sorular',
		'unupvoteda_qs_in_x' => '^ içerisindeki pozitif oylanmamış sorular',
		'unupvoteda_qs_title' => 'Pozitif oylanmamış son sorular',
		'upload_limit' => 'Çok fazla yükleme yaptınız. LÜtfen bir saat bekleyiniz.',
		'view_q_must_be_approved' => 'Soru sayfalarını görebilmeniz için üyeliğinizin onaylanması gerek.',
		'view_q_must_confirm' => 'Soru sayfalarını görebilmek için lütfen ^5e-posta adresinizi onaylayın^6.',
		'view_q_must_login' => 'Soru sayfalarını görebilmek için lütfen ^1giriş yapın^2 ya da ^3kayıt olun^4.',
		'viewed_qs_in_x' => '^ içerisindeki en çok görüntülenen sorular',
		'viewed_qs_title' => 'En çok görüntülenen sorular',
		'vote_disabled_approve' => 'Oylamadan önce üyeliğinizin onaylanması gerekmektedir.',
		'vote_disabled_down' => 'Negatif oylama hakkı sadece bazı kullanıcılara verilmiştir.',
		'vote_disabled_down_approve' => 'Negatif oy verebilmek için hesabınızın onaylanmış olması gerekmektedir.',
		'vote_disabled_hidden_a' => 'Gizli yanıtlara oy veremezsiniz.',
		'vote_disabled_hidden_q' => 'Gizli sorulara oy veremezsiniz.',
		'vote_disabled_level' => 'Sadece bazı kullanıcılar oy verebilir.',
		'vote_disabled_my_a' => 'Kendi yanıtınıza oy veremezsiniz.',
		'vote_disabled_my_q' => 'Kendi sorunuza oy veremezsiniz.',
		'vote_disabled_q_page_only' => 'Bu soruya oy vermek için soruyu görüntüleyin.',
		'vote_down_must_confirm' => 'Negatif oy verebilmek için ^5e-posta adresinizi onaylayın^6.',
		'vote_down_popup' => 'Negatif oy vermek için tıklayınız.',
		'vote_limit' => 'Çok fazla oy verildi. Lütfen bir saat sonra tekrar deneyiniz.',
		'vote_must_confirm' => 'Oy vermek için lütfen ^5e-posta adresinizi onaylayın^6.',
		'vote_must_login' => 'Oy vermek için lütfen ^1giriş yapın^2 ya da ^3kayıt olun^4',
		'vote_not_allowed' => 'Bunu oylamanıza izin verilmiyor.',
		'vote_up_popup' => 'Pozitif oylamak için tıklayın',
		'voted_down_popup' => 'Buna negatif oy verdiniz. Geri almak için tıklayın',
		'voted_qs_in_x' => '^ içerisindeki en yüksek oylanan sorular',
		'voted_qs_title' => 'En yüksek oylanan sorular',
		'voted_up_popup' => 'Buna pozitif oy verdiniz. Geri almak için tıklayın',
		'written' => '', // blank in English - placeholder for other languages
		'x_ago' => '^ önce',
		'x_answers' => '^ yanıt',
		'x_comments' => '^ yorum',
		'x_days' => '^ gün',
		'x_disliked' => '^ beğenmeme',
		'x_flags' => '^ işaretlenme',
		'x_hours' => '^ saat',
		'x_liked' => '^ beğenme',
		'x_minutes' => '^ dakika',
		'x_months' => '^ ay',
		'x_points' => '^ puan',
		'x_questions' => '^ soru',
		'x_seconds' => '^ saniye',
		'x_tags' => '^ etiket',
		'x_users' => '^ kullanıcı',
		'x_views' => '^ gösterim',
		'x_votes' => '^ oy',
		'x_weeks' => '^ hafta',
		'x_years' => '^ yıl',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
